### ISSUE TITLE
Feature Request: Hurt Effect Overlay Removal for Vehicle NPCs

### ISSUE THREAD

**Issue by tester2024** [AntonIT99/Flans-Mod-NPC-Vehicles#12]
I would like to request the addition of a feature that removes the hurt effect overlay for vehicle NPCs in Flan's Mod NPC Vehicles. Currently, when vehicle NPCs take damage, the red hurt effect overlay appears, which can be visually distracting. This feature request is to remove or disable this effect specifically for vehicle NPCs

![image](https://github.com/AntonIT99/Flans-Mod-NPC-Vehicles/assets/124782291/0acf7ca0-40aa-4a3d-a784-c29aa0f337bb)

**Comment by AntonIT99** [comment]
This is a good suggestion. I will implement it.
